# This workflow will do a clean installation of the dependencies and builds the source code
name: build

on: 
  pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    # Checkouts out of the repo
    - name: Checkout repo
      uses: actions/checkout@v3
      
#     - name: Install dependencies
#       run: npm install

    # Similar to npm install, but with some differences 
    - name: Install dependencies
      run: npm ci
      
    # Builds the program 
    - name: Run build
    - run: npm run build --if-present
