# This workflow will print a message, according to the type of the pull request that happens.
name: pull_request
       
on:
  pull_request:
    types: [review_requested]
  pull_request_target:
    types:
      - closed
  pull_request_review:
    types: [submitted,edited, dismissed]    

jobs:
  # If the pull request is closed it will print a message
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  # If the pull request is approved it will print a message
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

  # If the pull request is dismissed it will print a message    
  dismissed:
     if: github.event.review.state == 'dismissed'
     runs-on: ubuntu-latest
     steps:
       - run: echo "This PR was dismissed"
       
  # If the pull request is edited it will print a message     
  edited:
     if: github.event.review.state == 'edited'
     runs-on: ubuntu-latest
     steps:
       - run: echo "This PR was edited"     
  
