# This workflow will do a clean installation of the dependencies and builds the source code.
# If the pull request is on develop and it's accepted then it's like having a reviewed push.
# If the pull request is on main and it's accepted then we do the cd part.
name: pull_request
       
on: pull_request

jobs:
  push: 
    env:
      PORT: 3001
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PLATFORM_URI: ${{ secrets.PLATFORM_URI }}
      SERVER_URI:  ${{ secrets.SERVER_URI }}
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
            
      # Install the dependencies  
      - name: Install dependencies
        run: npm install

#       # Similar to npm install, but with some differences 
#       - name: Install dependencies
#         run: npm ci

      # # Runs the tests 
      # - name: Run test
      #   run: npm test

      # # Create Linters      
      # - name: Code Linting
      #   run: npm run lint

      # Create super-linters
#       - name: Install Liners
#         uses: github/super-linter@v4
#         env:
#           VALIDATE_ALL_CODEBASE: true
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cd: 
    runs-on: ubuntu-latest
    needs: push
    # If the pull request is on main and itw accepted
    if: github.ref == 'refs/heads/main'  && github.event.pull_request.merged == true
    steps: 
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ~/se2/1/se2-backend
            git reset --hard origin/main
            git pull https://${{secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-1 main
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-1'
          
