# This workflow will do a clean installation of the dependencies and builds the source code
# Push will only be available at the branches 
name: push
       
on: push

jobs:
  push_actions: 
    env:
      PORT: 3001
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PLATFORM_URI: ${{ secrets.PLATFORM_URI }}
      SERVER_URI:  ${{ secrets.SERVER_URI }}
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
            
      # Install the dependencies  
      - name: Install dependencies
        run: npm install

      # Runs all the tests serially
      - name: Run all the tests 
        run: npm test -- --serial
