# This workflow will do a clean installation of the dependencies and builds the source code
# Push will only be available at the branches 
name: push
       
on: push

jobs:
  push: 
    env:
      PORT: ${{ secrets.SSH_PORT }}
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PLATFORM_URI: ${{ secrets.PLATFORM_URI }}
      SERVER_URI:  ${{ secrets.SERVER_URI }}
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
            
      # Install the dependencies  
      - name: Install dependencies
        run: npm install

#       # Similar to npm install, but with some differences 
#       - name: Install dependencies
#         run: npm ci

      # # Runs the tests 
      # - name: Run test
      #   run: npm test

      # # Create Linters      
      # - name: Code Linting
      #   run: npm run lint

      # Create super-linters
#       - name: Install Liners
#         uses: github/super-linter@v4
#         env:
#           VALIDATE_ALL_CODEBASE: true
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
