# This workflow will do a clean installation of the dependencies and builds the source code
# Push will only be available at the branches 
name: push
       
on: push

jobs:
  push_actions: 
    env:
      PORT: 3001
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PLATFORM_URI: ${{ secrets.PLATFORM_URI }}
      SERVER_URI:  ${{ secrets.SERVER_URI }}
      SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      
    runs-on: ubuntu-latest
    steps:
      # Checkouts out of the repo
      - name: Checkout repo
        uses: actions/checkout@v3
            
      # Install the dependencies  
      - name: Install dependencies
        run: npm install

      # Runs all the tests serially
      - name: Run all the tests 
        run: npm test -- --serial

      # Run all the tests individually
      # # Runs the tests on init
      # - name: Run test on init
      #   run: npm test tests/init.test.js

      # # Runs the tests on dashboard
      # - name: Run test on dashboard
      #   run: npm test tests/routes_dashboard.test.js

      # # Runs the tests on dashboard2
      # - name: Run test on dashboard
      #   run: npm test tests/routes_dashboard2.test.js

      # # Runs the tests on general
      # - name: Run test on general
      #   run: npm test tests/routes_general.test.js

      # # Runs the tests on sources
      # - name: Run test on sources
      #   run: npm test tests/routes_sources.test.js

      # # Create Linters      
      # - name: Code Linting
      #   run: npm run lint

      # Create super-linters
#       - name: Install Liners
#         uses: github/super-linter@v4
#         env:
#           VALIDATE_ALL_CODEBASE: true
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
