# This workflow will do a clean installation of the dependencies and builds the source code
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    # Checkouts out of the repo
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
#     - name: Install dependencies
#       run: npm install

    # Similar to npm install, but with some differences 
    - name: Install dependencies
      run: npm ci
      
    # Runs the tests if they exist
    - name: Run test
      run: npm test --if-present
